# propiedades para entorno desarrollo
# spring.profiles.active=dev
server:  port: 8080
  servlet:    context-path: /demo
  
#Configurando el dataSource
spring:
  datasource:
    name: jdbc/DEMO
    username: DEMO
    password: 12345678
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    driver-class-name: oracle.jdbc.driver.OracleDriver
 
 
  #Configuracion del liquibase
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:/script/master_integrado_continuo.yaml
    contexts: test,mocks
   
   #Configuracion el jpa
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        "[use_sql_comments]": true
        "[format_sql]": true
        
  output:
    ansi:
      enabled: detect 
      
#Configuraciones para la documentacion viva
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    oauth2-redirect-url: /security/login

logging:  config: classpath:log4j2/log4j2-console.yaml