# propiedades para entorno de pruebas de integracion
# spring.profiles.active=it

server:
  port: 8080
  servlet:
    context-path: /demo
       
  
spring:
  # Configuracion para la base de datos en memoria  
  datasource:
    name: jdbc/DEMO_IT
    username: sa
    password: sa
    url: jdbc:h2:mem:mydb;MODE=ORACLE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS DEMO
    driver-class-name: org.h2.Driver
    
  h2:
    console:
      enabled: true
      path: /h2-console
  
  liquibase:   enabled: true
   drop-first: true
   change-log: classpath:/script/master_integrado_continuo.yaml
   contexts: test,mocks
   
    jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect    hibernate:      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        "[use_sql_comments]": true
        "[format_sql]": true

logging:
  config: classpath:log4j2/log4j2-console.yaml